CREATE TABLE IF NOT EXISTS `#__profiles_families` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `ordering` int(11) NOT NULL,
  `state` tinyint(1) NOT NULL default '1',
  `checked_out` int(11) NOT NULL,
  `checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
  `user_id` int(11) NOT NULL,
  `first_name` varchar(255) NOT NULL,
  `spouse_name` varchar(255) NOT NULL,
  `last_name` varchar(255) NOT NULL,
  `video` varchar(255) NOT NULL,
  `pdf` varchar(255) NOT NULL,
  `about_us` text NOT NULL,
  `about_us_image` varchar(255) NOT NULL,
  `our_home` text NOT NULL,
  `our_home_image` varchar(255) NOT NULL,
  `ext_family` text NOT NULL,
  `ext_family_image` varchar(255) NOT NULL,
  `ext_family_image_spouse` varchar(255) NOT NULL,
  `family_traditions` text NOT NULL,
  `family_traditions_image` varchar(255) NOT NULL,
  `adoption_story` text NOT NULL,
  `adoption_story_image` varchar(255) NOT NULL,
  `dear_birthmother` text NOT NULL,
  `adopt_gender` varchar(255) NOT NULL,
  `adopt_race` mediumtext NOT NULL,
  `seo_title` varchar(100) NOT NULL,
  `seo_keywords` varchar(255) NOT NULL,
  `seo_description` varchar(255) NOT NULL,
  `my_occupation` varchar(255) NOT NULL,
  `spouse_occupation` varchar(255) NOT NULL,
  `my_religion` varchar(255) NOT NULL,
  `spouse_religion` varchar(255) NOT NULL,
  `my_education` varchar(255) NOT NULL,
  `spouse_education` varchar(255) NOT NULL,
  `my_food` varchar(255) NOT NULL,
  `spouse_food` varchar(255) NOT NULL,
  `my_sport` varchar(255) NOT NULL,
  `spouse_sport` varchar(255) NOT NULL,
  `my_hobby` varchar(255) NOT NULL,
  `spouse_hobby` varchar(255) NOT NULL,
  `my_music_group` varchar(255) NOT NULL,
  `spouse_music_group` varchar(255) NOT NULL,
  `my_movie` varchar(255) NOT NULL,
  `spouse_movie` varchar(255) NOT NULL,
  `my_vacation_spot` varchar(255) NOT NULL,
  `spouse_vacation_spot` varchar(255) NOT NULL,
  `my_holiday` varchar(255) NOT NULL,
  `spouse_holiday` varchar(255) NOT NULL,
  `my_tv_show` varchar(255) NOT NULL,
  `spouse_tv_show` varchar(255) NOT NULL,
  `my_subject_in_school` varchar(255) NOT NULL,
  `spouse_subject_in_school` varchar(255) NOT NULL,
  `my_book` varchar(255) NOT NULL,
  `spouse_book` varchar(255) NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 ;

CREATE TABLE IF NOT EXISTS `#__profiles_photos` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `ordering` int(11) NOT NULL,
  `state` tinyint(1) NOT NULL default '1',
  `checked_out` int(11) NOT NULL,
  `checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
  `family_id` int(5) NOT NULL,
  `path` varchar(255) NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 ;

CREATE TABLE IF NOT EXISTS `#__profiles_recents` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `ordering` int(11) NOT NULL,
  `state` tinyint(1) NOT NULL default '1',
  `checked_out` int(11) NOT NULL,
  `checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
  `first_name` varchar(255) NOT NULL,
  `spouse_name` varchar(255) NOT NULL,
  `last_name` varchar(255) NOT NULL,
  `rotator_top` varchar(55) NOT NULL,
  `rotator_bottom` varchar(55) NOT NULL,
  `recent_story` text NOT NULL,
  `recent_story_image` varchar(255) NOT NULL,
  `seo_title` varchar(100) NOT NULL,
  `seo_keywords` varchar(255) NOT NULL,
  `seo_description` varchar(255) NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 ;

CREATE TABLE IF NOT EXISTS `#__profiles_successes` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `ordering` int(11) NOT NULL,
  `state` tinyint(1) NOT NULL default '1',
  `checked_out` int(11) NOT NULL,
  `checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
  `first_name` varchar(255) NOT NULL,
  `spouse_name` varchar(255) NOT NULL,
  `last_name` varchar(255) NOT NULL,
  `success_story` text NOT NULL,
  `success_story_image` varchar(255) NOT NULL,
  `seo_title` varchar(100) NOT NULL,
  `seo_keywords` varchar(255) NOT NULL,
  `seo_description` varchar(255) NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 ;